const modules=[
['Antes da Primeira Muda','O plantio começa antes de chegar ao campo. Defina o objetivo da produção — consumo próprio, complemento de renda ou comercialização — pois ele influencia área, estrutura e investimento.',['Use uma pequena área como laboratório de aprendizagem.','Observe manejo, irrigação, tempo exigido e custos não previstos.','Expanda depois de dominar o processo.']],
['Conhecendo a Área','Antes de definir a quantidade de mudas, observe a propriedade de forma atenta.',['Luz e disponibilidade de água.','Acesso, relevo e drenagem.','Solo e vegetação já existente.','Para objetivo comercial, fundamente decisões com análise de solo e orientação técnica.']],
['Preparando o Terreno','Planeje a posição das plantas, as linhas, os corredores, o acesso, a irrigação e o espaço para manutenção futura.',['O espaçamento depende da cultivar, sistema produtivo, fertilidade, topografia e objetivo comercial.','Para implantação comercial, utilize recomendação agronômica específica para sua região.']],
['As Mudas','A qualidade da muda influencia diretamente o sucesso da implantação.',['Observe aparência vigorosa e sadia.','Avalie desenvolvimento, estrutura e raízes.','Verifique danos, enfermidades e procedência.']],
['Chegou a Hora de Plantar','A implantação representa a passagem do planejamento para a produção no campo.',['Manipule a muda com cuidado e evite danos às raízes.','Posicione no berço de plantio, acomode o solo e observe a estabilidade.','A irrigação inicial deve respeitar as condições locais.']],
['Irrigação','A disponibilidade de água deve ser planejada desde o começo. O manejo depende de fatores integrados.',['Considere clima, temperatura, solo, chuva, idade da planta e época do ano.','Mais água nem sempre significa melhor.','Observe solo, clima e resposta visual das plantas.']],
['Acompanhando o Desenvolvimento','O bananal “fala” com o produtor por sinais visuais. A vistoria sistemática é indispensável.',['Observe folhas, crescimento e umidade do solo.','Identifique cedo pragas, danos e competição de plantas espontâneas.','Confira a irrigação em todas as linhas.']],
['Não Espere o Problema Ficar Grande','Acompanhar periodicamente permite identificar problemas enquanto ainda são pequenos.',['Corrija falhas de irrigação.','Substitua mudas perdidas rapidamente.','Observe sintomas e reduza o risco de perdas severas.']],
['Aprenda a Registrar','Fotografe, filme, anote e compare. Registros periódicos criam uma linha do tempo da plantação.',['Registre no Dia 0.','Compare aos 30, 60 e 90 dias.','Use imagens para perceber crescimento ou declínio.']],
['Transformando o Plantio em Negócio','Quando o objetivo é comercial, o produtor também precisa agir como gestor.',['Registre mudas, preparação, adubação e ferramentas.','Inclua irrigação, mão de obra, transporte, energia e manutenção.','Sem conhecer os custos, não é possível avaliar o resultado financeiro.']],
['Mortalidade e Reposição','Registre a quantidade implantada, as perdas ao longo dos meses e as reposições.',['A taxa de sobrevivência é: mudas vivas ÷ mudas plantadas × 100.','Acompanhar esse número é vital para a saúde financeira e produtiva.']],
['8 Erros de Quem Está Começando','O manual reúne oito erros recorrentes que comprometem organização e acompanhamento.',['Comprar sem planejar.','Ignorar a disponibilidade de água.','Plantar sem linhas e corredores.','Esquecer o tamanho final das plantas.','Abandonar após o plantio.','Não registrar despesas.','Expandir antes de dominar a área menor.','Copiar técnicas sem considerar condições locais.']],
['Quando é Hora de Expandir?','Expandir deve ser consequência de um processo que já funciona.',['Avalie irrigação e sobrevivência.','Confirme capacidade de manejo e conhecimento dos custos.','Verifique recursos financeiros e destino comercial da produção.']],
['Cronograma de Acompanhamento','Uma rotina simples e organizada orienta os primeiros registros.',['Dia 0: implantação e fotografias.','Primeira semana: adaptação, estabilidade e irrigação.','30 dias: sobrevivência e folhas novas.','60 dias: comparação fotográfica.','90 dias: vigor e limpeza da área.']]
];
const checklistItems=['Definir o objetivo da produção','Observar luz, água, acesso, relevo e drenagem','Planejar linhas, corredores e irrigação','Verificar qualidade e procedência das mudas','Registrar quantidade e localização no Dia 0','Fotografar a implantação','Programar as vistorias de 30, 60 e 90 dias','Organizar o registro de despesas'];
const storage={get(k,f){try{return JSON.parse(localStorage.getItem(k))??f}catch{return f}},set(k,v){try{localStorage.setItem(k,JSON.stringify(v))}catch{}}};
let completed=storage.get('araguaia-modules',[]);let checked=storage.get('araguaia-checklist',[]);
const list=document.querySelector('#module-list');
modules.forEach((m,i)=>{const article=document.createElement('article');article.className='module';article.innerHTML=`<button class="module-heading" aria-expanded="false" aria-controls="module-${i}"><span class="num">${String(i+1).padStart(2,'0')}</span><h3>${m[0]}</h3><span class="toggle" aria-hidden="true">+</span></button><div class="module-panel" id="module-${i}"><div><p>${m[1]}</p><ul>${m[2].map(x=>`<li>${x}</li>`).join('')}</ul></div><button class="complete ${completed.includes(i)?'done':''}" data-index="${i}">${completed.includes(i)?'Módulo concluído ✓':'Marcar como concluído'}</button></div>`;list.append(article)});
list.addEventListener('click',e=>{const heading=e.target.closest('.module-heading');if(heading){const panel=document.querySelector('#'+heading.getAttribute('aria-controls'));const open=heading.getAttribute('aria-expanded')==='true';heading.setAttribute('aria-expanded',String(!open));panel.classList.toggle('open',!open)}const btn=e.target.closest('.complete');if(btn){const i=+btn.dataset.index;completed=completed.includes(i)?completed.filter(x=>x!==i):[...completed,i];storage.set('araguaia-modules',completed);btn.classList.toggle('done');btn.textContent=completed.includes(i)?'Módulo concluído ✓':'Marcar como concluído';updateProgress()}});
function updateProgress(){document.querySelector('#progress-label').textContent=`${completed.length} de 14`;document.querySelector('#progress-bar').style.width=`${completed.length/14*100}%`};updateProgress();
document.querySelector('#reset-progress').onclick=()=>{completed=[];storage.set('araguaia-modules',completed);document.querySelectorAll('.complete').forEach(b=>{b.classList.remove('done');b.textContent='Marcar como concluído'});updateProgress()};
const checklist=document.querySelector('#checklist');function renderChecklist(){checklist.innerHTML=checklistItems.map((x,i)=>`<label class="check-item"><input type="checkbox" data-index="${i}" ${checked.includes(i)?'checked':''}><span>${x}</span></label>`).join('')}renderChecklist();checklist.onchange=e=>{const i=+e.target.dataset.index;checked=e.target.checked?[...new Set([...checked,i])]:checked.filter(x=>x!==i);storage.set('araguaia-checklist',checked)};document.querySelector('#clear-checklist').onclick=()=>{checked=[];storage.set('araguaia-checklist',checked);renderChecklist()};
const currency=new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL'});function updateCost(){const total=+document.querySelector('#investment').value;const qty=+document.querySelector('#seedlings').value;const out=document.querySelector('#cost-result strong');out.textContent=total>=0&&qty>0?currency.format(total/qty):'—'}function updateSurvival(){const planted=+document.querySelector('#planted').value;const alive=+document.querySelector('#alive').value;const out=document.querySelector('#survival-result strong');out.textContent=planted>0&&alive>=0&&alive<=planted?`${(alive/planted*100).toLocaleString('pt-BR',{maximumFractionDigits:1})}%`:'—'}document.querySelector('#cost-form').onsubmit=e=>{e.preventDefault();updateCost()};document.querySelector('#survival-form').onsubmit=e=>{e.preventDefault();updateSurvival()};['investment','seedlings'].forEach(id=>document.querySelector('#'+id).addEventListener('input',updateCost));['planted','alive'].forEach(id=>document.querySelector('#'+id).addEventListener('input',updateSurvival));
const checkoutUrl=window.ARAGUAIA_CONFIG?.checkoutUrl||'';document.querySelectorAll('.checkout-link').forEach(link=>link.addEventListener('click',e=>{if(!checkoutUrl||checkoutUrl.includes('SEU_CODIGO')){e.preventDefault();document.querySelector('#comprar').scrollIntoView({behavior:'smooth'});const status=document.querySelector('#checkout-status');status.textContent='Insira o link do seu checkout Hotmart no arquivo config.js para ativar o pagamento.';return}link.href=checkoutUrl;link.target='_blank';link.rel='noopener'}));
const menu=document.querySelector('.menu-toggle'),nav=document.querySelector('#main-nav');menu.onclick=()=>{const open=menu.getAttribute('aria-expanded')==='true';menu.setAttribute('aria-expanded',String(!open));nav.classList.toggle('open',!open)};nav.onclick=e=>{if(e.target.matches('a')){nav.classList.remove('open');menu.setAttribute('aria-expanded','false')}};
